### ISSUE TITLE
increase overall test coverage

### ISSUE THREAD

**Issue by silkentrance** [pana-cc/mocha-typescript#104]
summary says it all

```
Statements   : 89.9% ( 347/386 )
Branches     : 78.9% ( 172/218 )
Functions    : 94.17% ( 97/103 )
Lines        : 89.92% ( 339/377 )
```

Branch coverage is currently the problem here.

It seems as if latest changes induced by #89 or #90 might have caused a regression here.

**Comment by pana-cc** [comment]
Any idea of tool that can display properly the code coverage in VSCode? "Coverage Gutters" is somewhat fine.

**Comment by silkentrance** [comment]
Yeah, I was about to fix the current coverage problem with the report I get from nyc.

**Comment by silkentrance** [comment]
@pana-cc Did you just remove the PR for your refactoring? Why?

**Comment by silkentrance** [comment]
I think that the goal was reached.
