### ISSUE TITLE
Refactor all standard tdd / bdd tests to not use prebound functions

### ISSUE THREAD

**Issue by silkentrance** [pana-cc/mocha-typescript#110]
Mocha does not support prebound functions as in

```
describe('suite', () => {
   it ('something', () => {});
});
```

instead one must use unbound functions, as in

```
describe('suite', function () {
   it ('something', function () {});
});
```

**Comment by silkentrance** [comment]
Also we must check whether we use prebound functions for our object oriented suites...

**Comment by pana-cc** [comment]
I think it supports lambda functions, but you loose the `this` context, it is ok as long as you don't need it.

**Comment by silkentrance** [comment]
Yes, that is why. If you are ok with that, then we can leave it as is.

**Comment by silkentrance** [comment]
Closing as it is not an issue.
