### ISSUE TITLE
Use mocha-typescript in Storybook

### ISSUE THREAD

**Issue by arieldf** [pana-cc/mocha-typescript#111]
Hi!

We have recently set up Storybook in our team and want to integrate our tests using https://github.com/mthuret/storybook-addon-specifications. I have followed the instructions for using mocha and I am getting the error "TypeError: decorator is not a function
    at DecorateProperty (http://localhost:9001/static/preview.bundle.js:120509:33).

Have anyone managed to get this to work and is it possible, is seems it is only the BDD-style that is highlighted in the docs? I feel this might be a longshot and I wanted to ask after several hours of trying.

Feel free to just close this if it is this issue does not belong here.

Best regards,
Ariel

**Comment by silkentrance** [comment]
The link you provided does not help very much. Maybe you can provide us with the stack trace?

Apart from that I think that you need to also import typescript somewhere along the line, with the decorators feature enabled.

**Comment by silkentrance** [comment]
@arieldf ping any news on that subject?

**Comment by silkentrance** [comment]
Closing as there has been no reply for a month now.
