### ISSUE TITLE
Deprecated type definitions

### ISSUE THREAD

**Issue by hubbergit** [pana-cc/mocha-typescript#116]
tslint@5.11.0 reports the following linter error

`test is deprecated: use 'Mocha.TestFunction' instead.`

 when linting my test code while using mocha@5.2.0 and mocha-typescript@1.1.17

**Comment by pana-cc** [comment]
I've added the versions you mention in the [mocha-typescript-seed](https://github.com/pana-cc/mocha-typescript-seed) repo and it seems to compile fine. Can you clone the repo and reproduce the error? Maybe I am missing something?

**Comment by hubbergit** [comment]
@pana-cc Please reopen this issue, because I have provided a reproducable case.

**Comment by chadbr** [comment]
Is there some 'working combination' that I can roll back to get me going?

I'm trying to upgrade to TS 3.x, etc... but this one is holding me back.

trying with 'all the latest'

```
  "devDependencies": {
    "@types/mocha": "^5.2.5",
    "mocha": "^5.2.0",
    "mocha-junit-reporter": "1.18.0",
    "mocha-typescript": "1.1.17",
    "ts-node": "~7.0.0",
    "tslib": "^1.9.3",
    "tslint": "~5.11.0",
    "typescript": "~3.1.3"
  },
```

**Comment by chadbr** [comment]
aha --! 

I fixed my issue... 

I had @types/node in my package.json, and 
```
    "types" : [
      "node"
    ]
```
in my tsconfig.json

removing both removes all errors related to mocha-typescript

it may cause me some issues in other projects, but it's a start...

**Comment by mscharley** [comment]
By adding `"types": [ "node" ]`, you're saying the only ambient types in any part of the project is from node. When running mocha, this isn't true - many of the mocha types are ambiently available too. Removing the `types` option should do the right thing for you. Alternatively, adding `"mocha"` to the list should fix things too (if I recall correctly - I usually let TypeScript do it's thing and manage this for me.)

**Comment by ksaifullah** [comment]
I'm getting the same warning.
Subscribing to the topic if anyone finds any work around.
<img width="762" alt="screen shot 2018-12-03 at 11 17 53 pm" src="https://user-images.githubusercontent.com/7429101/49373301-b8d24600-f751-11e8-8238-a6f1500c0e66.png">

**Comment by mscharley** [comment]
The current best-case work around is to downgrade some of the `@types` packages you're using (mocha at the very least, not sure about others) or sprinkle `// tslint:disable:deprecation` at the top of your test files or just disable that rule globally.

**Comment by pana-cc** [comment]
Guys, I had some time to update the typings in mocha-typescript.
Could you give it a try: https://github.com/pana-cc/mocha-typescript/pull/118
Checkout the "fix-deprecation" branch, then "npm i", "npm pack" in the mocha-typescript repo and install the .tgz in your projects to test if it is fine.

**Comment by hubbergit** [comment]
Works for me! Thanks a lot.

**Comment by hubbergit** [comment]
@pana-cc Would be great, if you could release a new version that incorporates these changes.

**Comment by pana-cc** [comment]
Over the weekend.

**Comment by silkentrance** [comment]
@pana-cc what is the status of this? did you already publish the release?

**Comment by silkentrance** [comment]
Priorly, types/mocha was a runtime dependency and not a dev dependency, so it came with the installation of the tgz from the current version of mocha-typescript.

That being said, does it really make any sense of having a with/without types/mocha scenario in the tests? Not that it will take extra time, but the other project will definitely need the types/mocha package, otherwise tsc will complain.

**Comment by silkentrance** [comment]
@pana-cc I think that the watcher tests can be put aside for the time being, as the windows platform seems more or less unreliable when it comes to signalling and timely termination of processes.

**Comment by silkentrance** [comment]
@pana-cc of course we can always also be tackling #133 first, simplifying the previous definition, i.e. export only suite and test and params.

**Comment by silkentrance** [comment]
@pana-cc with #159 in place, and which is working like a charm, this can surely be closed, don't you think?

**Comment by hubbergit** [comment]
@silkentrance I think the idea of @pana-cc was to close this issue once the fix is released. Is it released?

**Comment by silkentrance** [comment]
@hubbergit yes, I know. I just wanted to point him to the fact that with #159 and the refactoring done in #157, the overall typings became much simpler.

**Comment by silkentrance** [comment]
Closing this now as we are heading for 2.0.0.
