### ISSUE TITLE
Duplicating core Mocha functionality in tssd() is redundant

### ISSUE THREAD

**Issue by silkentrance** [pana-cc/mocha-typescript#120]
In line 627ff it reads:

```
        context.xit = context.xspecify = context.it.skip = function(title) {
            context.it(title);
        };
```

Shouldn't we be calling common.test.skip instead?

**Comment by silkentrance** [comment]
Maybe the whole tbdd() shebang can be obsoleted... investigating.

**Comment by pana-cc** [comment]
It is indeed redundant. It was painful to copy that code into the repo, but it was the way to ensure the: #122

**Comment by silkentrance** [comment]
@pana-cc I can imagine that. However, without that code, it works just fine. As for the OOP interface, the user needs to import additional stuff, such as the `@test` decorator, which would otherwise overwrite the existing declarative `test` function, if I am correct.

**Comment by silkentrance** [comment]
@pana-cc consider this an experiment for now.
