### ISSUE TITLE
Become one of the built-in mocha test UIs

### ISSUE THREAD

**Issue by pana-cc** [pana-cc/mocha-typescript#122]
At some point decorators will become a standard and wildly adopted and implemented. This will allow decorators to be used in pure browser and node JavaScript. At that point the goal for this repo should be to provide well tested decorators based OOP style mocha test UI.

Ultimately mocha-typescript should be merged into mocha itself. Either standing as "oop" near the well known "tdd" and "bdd" or by merging the functionality into the existing "tdd" and "bdd".

**Comment by silkentrance** [comment]
@pana-cc While this might be the case, mocha is still plain Javascript and not depending on Typescript at all, just supporting it via externally provided typings.

**Comment by pana-cc** [comment]
That's a long shot, but if decorators become a standard thing in JavaScript, then the mocha-typescript interface will be usable in plain JavaScript.

**Comment by silkentrance** [comment]
See #133. This can never be realised are we are inherently incompatible to the standard tdd/bdd interface. What we do support, though, is provide the user a seamless transition to the object oriented interface that mocha-typescript offers.

So we should focus on that and make it our main selling point, so to speak.

**Comment by pana-cc** [comment]
Ok, let's agree to disagree here. I am not going to reopen the issue, but I'd happy to contribute pieces of this software to mocha. I am going to ping mocha for opinions. Let's focus on the pending PRs now.

**Comment by silkentrance** [comment]
@pana-cc 😄 yes, since this is your project, I'd be happy to have this or even parts of it in mocha.
