### ISSUE TITLE
Timeout tests are failing again on appveyor

### ISSUE THREAD

**Issue by silkentrance** [pana-cc/mocha-typescript#134]
It seems as if the VMs on appveyor are slower than on travis or even the local machine. Timeouts of 10ms or 20ms cannot be reached in time. I suggest that we increase the timeout limit to at least 100ms  and adjust the tests that are meant to be slow or that have to fail, accordingly.

@pana-cc see https://ci.appveyor.com/project/silkentrance/mocha-typescript/build/job/m5m2l6kd3dsglabl

**Comment by pana-cc** [comment]
Sounds fair. For development I usually use @only to execute small part of the tests so this should not slow down development much.
