### ISSUE TITLE
I am able to understand the way to generate dynamic suite, but how to generate dynamic test cases inside dynamic suite.

### ISSUE THREAD

**Issue by ittechsathish** [pana-cc/mocha-typescript#139]

**Comment by silkentrance** [comment]
@ittechsathish well it is basically the same as in standard mocha.
perhaps you want to look at the existing tests?
or even the documentation, see for example http://mocha-typescript.org/usage

However, and you are correct in that the documentation is somewhat lacking as it is a WIP. What we need here is additional information on how to utilise the parameters for generated test suites and cases.

**Comment by silkentrance** [comment]
@ittechsathish The level of dynamism is limited by the test interface that you use.

For the object oriented suite classes, you can actually create these on the fly, however, limitations exist in the test methods as these cannot be added dynamically.

In comes the ``@params`` decorator which lets you run a given test method with different parameters.

In comes also the ability to define base classes and inherit from those.

Please have a look at the various tests located under ``test/it/`` which make extensive use of the ``@param`` decorator and the ``Abstract*ITBase`` classes which serve us for running different test scenarios.

Making this even more dynamic will require you to come up with an ingenious solution 😄 

And nobody limits you in calling dynamically created tests from these test methods, just as in the original mocha.

**Comment by silkentrance** [comment]
Documentation on parameterised tests has been updated. See #147 or the docs from the branch https://github.com/pana-cc/mocha-typescript/blob/gh-132/docs/oop_params.md and see whether this will fit your needs for further dynamism on test methods.

As for dynamic creation of mocha tests using the standard BDD/TDD interface, see the official mocha documentation.

**Comment by silkentrance** [comment]
@ittechsathish please have a look at #149 and see whether this will fit your needs.

**Comment by silkentrance** [comment]
I think that we have done all that we can do, especially with the existing code base which is all about dynamic creation of test suites and tests...

Closing as there has been no reaction from the OP.
