### ISSUE TITLE
Params is not included in typings

### ISSUE THREAD

**Issue by tklever** [pana-cc/mocha-typescript#141]
The following code
```typescript
import { params } from 'mocha-typescript';
```
will produce the following error: `TS2305: Module '"mocha-typescript"' has no exported member 'params'.`

To utilize params, one must currently tell the compiler to ignore like this:
```typescript
//@ts-ignore
import { params } from 'mocha-typescript';
```

**Comment by silkentrance** [comment]
@tklever We are waiting for feedback from you. While the PR is just fine, we would like to have some additional information, as our tests show that they will work just fine without the changes from your PR.
