### ISSUE TITLE
Dependency injection support is broken

### ISSUE THREAD

**Issue by silkentrance** [pana-cc/mocha-typescript#158]
The handler's handles and create method will always be called with the suite class instead of the to be injected class that is an expected parameter of either hook or test method.

I would expect the system to call the handles/create for each parameter of either a hook method or test method.

**Comment by silkentrance** [comment]
Or is this passing of the suite class specific to the typedi ioc? if so, will this work at all with the other available IOCs such as

- https://github.com/thiagobustamante/typescript-ioc
- https://github.com/inversify/InversifyJS

... and so on.

**Comment by silkentrance** [comment]
Reading from the available test suite for typedi, it seems that we support constructor injects only.

**Comment by silkentrance** [comment]
In the future we also require dependency injection on hooks, and test methods alike.

**Comment by pana-cc** [comment]
I think we support injects on constructors only, but that’s why the registration takes an object - so we can extend it with optional methods that will inject in hooks, methods, etc.

**Comment by silkentrance** [comment]
Great. We need to investigate this further. Including also reflect-metadata.

**Comment by silkentrance** [comment]
Closing for now.
