### ISSUE TITLE
currentTest.state mocha

### ISSUE THREAD

**Issue by truhlikfredy** [pana-cc/mocha-typescript#17]
Hi, 

I like your approach to mocha. I had in **after** methods small code which changed behavior depending if the test failed or not, i was able to check value of the **currentTest.state** and if it was "failed" i could have different logic. Is it possible here as well?

**Comment by pana-cc** [comment]
It is `this.currentTest.state` right? The functions that are executed are class methods and their this is the class instance. So the this in the decorators based interface is not the mocha context passed to it/before/after. I guess I can set somewhat instance field on the test class instance when running test. A sample usage would be:

```
@suite class MyClassThatNeedsTheContext {
  context: MochaContext /* not sure about the name and type, or if the context should be spread so all test properties be available on the class */;
  after() {
    this.context.currentTest.state;
    // or if spread
    this.currentTest.state;
  }
}
```
The second will pollute a lot and may collide with properties on the class.

To avoid collisions the field that will hold the context may be marked with decorator.
```
@suite class MyClass {
  @context mocha;
  after() {
    this.mocha.currentTest.state;
  }
}
```

I am not sure what would be the best approach to expose the mocha context (the this).

The implementation won't be technically challenging though.

**Comment by truhlikfredy** [comment]
It doesn't have to be same implementation as in mocha. Important is just to have it. The decorator marking seams to me better.

**Comment by pana-cc** [comment]
Hi,
This has been trickier than I expected but is now live in 1.0.20.
Here is the test, you can find out how it works:
https://github.com/pana-cc/mocha-typescript/blob/master/tests/context.suite.ts#L18
There is also slight README.md update near the "In case you really really need the mocha context"

**Comment by truhlikfredy** [comment]
Oh, lovely, excellent job I will give it try this week.
