### ISSUE TITLE
Good support for parametrizet testing

### ISSUE THREAD

**Issue by truhlikfredy** [pana-cc/mocha-typescript#20]
In mocha it's very easy and pleasant to create parametrized tests even running multiple tests inside them:

Often I have array of tests, each containing most likely title, input values and expected results

```
  objLoginObjects.forEach(function(test) {
    it("first step " + test.title + " [regular]", function(done){
      ....
    })

    it("2nd step " + test.title + " [regular]",function(done){
      ....
    })

    it("test last step" + test.title + " and NO auth [regular]", function(done){
      ....
    })
  })
```

It's easy to remember and to do, allow lot of flexibility as well. Because moch-typescript is going the proper unit testing way where you have methods for each unit test. So this anarchy approach is not as easy to do.

I ended up doing one test case which was running all the other methods internally, but it's bit awkward and more work.

```
  valueSingle(test: any, done: Function) {
    ...
  }



  @test(Helper.pad("VALUE - ALL"))
  @timeout(2000)
  valueAll(done: Function) {
    for (const test of objLoginObjects) {
      await new Promise( (resolve) => { 
         //this.subTest(prefix, test, type);  // does output to the console progress
         valueSingle(test, resolve); });
    }
    done();
  }

```

It's not easy to remember and not even fast to do as it was in the original mocha, and there are few problems, now test counter is off, not counting the parametrized tests properly. The output is strange, because when there is error you don't know with what parameters it happened. And in the end I enede up creating Helper class and adding this for each loop there and adding console output line as well, where i imitate the padding, the color and your style  of printing.

But when I endedup doing Helper class to a framework then it's probably sign that the framework is missing features.

Being able to add ornament / annotation to a class something like 

```
@test("Authentification")
@testEach objLoginObjects
@testTitlePostfix(testItem.title)
login(done: Function, testItem: object) {
   ....
   done();
}
```

This way the tests would count up properly, if something fails you know which one it is. There wouldn't be any need for console output in the same style to match to show the progress. And you would get output something like this:

```
     Authentification - Empty string
     Authentification - Wrong password
     Authentification - Very long and wrong password
     Authentification - Numbers instead of string
     Authentification - Correct credentials
```

As you see this way you can test many different scenarios quickly to be more confident that your API will work as predicted. And I think it's important to have in testing framework, at the moment it is possible to achieve this only with workarounds. And end up with unnecessary methods and going bit against DRY as well. Because the unit tests end up only as invokers for other methods so they had only 1 line where I was calling the helper class to iterate the whole array.

**Comment by pana-cc** [comment]
This is the best I could think of:
``` TypeScript
import { suite, test } from "mocha-typescript";

@suite class Static {
    @test one() {
    }
}

[
    { url: "google.com", title: "google" },
    { url: "github.com", title: "github" },
    { url: "npmjs.com", title: "npmjs" }
].forEach(({ url, title }) => {
    // Nice question: How to share the same instance for all tests?
    @suite(`OAuth ${title}`) class OAuthTest {
        @test async "Request token"() {
            // return (await request(url)).responce.headers.token;
            return Promise.resolve();
        }
        @test async "Exchange token for oauth session"() {
            return Promise.resolve();
        }
        @test async "Request sensitive data"() {
            return Promise.resolve();
        }
    }
});
```

The output is:
```
Run mocha.


  Static
    ✓ one

  OAuth google
    ✓ Request token
    ✓ Exchange token for oauth session
    ✓ Request sensitive data

  OAuth github
    ✓ Request token
    ✓ Exchange token for oauth session
    ✓ Request sensitive data

  OAuth npmjs
    ✓ Request token
    ✓ Exchange token for oauth session
    ✓ Request sensitive data


  10 passing (12ms)

```
In case of "generated" tests it may be better to stick with describe/it API.

**Comment by pana-cc** [comment]
I am fan of this feature and it's been bothering my mind for a while but I can't seem to settle on a solution so I think I will close it and keep the above example in the readme. Ultimately something like dependency injection should be used to populate a field with the data, but then additional mechanism to name the tests should be provided in the @suite decorator. Then when the data is provided through the decorator it is hard to strongly type it. IDK, if someone could contribute an elegant solution (or at least the idea for the API) I'd be glad to reopen this and push it forward.
