### ISSUE TITLE
Double test entries in output

### ISSUE THREAD

**Issue by henioStraszny** [pana-cc/mocha-typescript#21]
Hello, 

First of all, thank you for your great work :+1:  

My problem is following, I see each test double in the output, it looks like one is redundant:
 
```Run mocha.

    DefaultDeleteTest name should be equal to: '/':
  √ DefaultDeleteTest name should be equal to: '/': 1ms
    DefaultDeleteTest method should be equal to: Get():
  √ DefaultDeleteTest method should be equal to: Get(): 1ms

  2 passing (13ms)
```

Test class:
```typescript
@suite class DefaultDeleteTest {
    @test 'name should be equal to: \'/\''() {
        let defaultDelete = new DefaultDelete();
        chai.expect(defaultDelete.Name).to.equal('/');
    }
    @test 'method should be equal to: Get()'() {
        let defaultDelete = new DefaultDelete();
        chai.expect(defaultDelete.HttpMethod).to.equal(HttpVerb.delete);
    }
}
```

I run mocha with following command:

```powershell
C:\Source> .\node_modules\.bin\mocha-typescript-watch --opts mocha-ts.opts
```

mocha-ts.opts
```powershell
--require ts-node/register
--compilers ts:ts-node/register,tsx:ts-node/register
--reporter list
--watch-extensions tsx,ts
--recursive
test/
```

I know that it looks as minor or some silly problem, but I would appreciate any help.

**Comment by pana-cc** [comment]
I think the line reader I am using to read and write output from the mocha can not handle the output of the list reporter. I suspect the line reporter writes the name of the test and later when the test passes or fails it erases the line and rewrites it with the status and duration added. The mocha-typescript line reader however somehow strips any carriage return characters from the line and the result is a second line. For now you can change the "list" reporter to the default one. I will keep the issue open, I may find a proper solution later.

**Comment by pana-cc** [comment]
Another source for the problem may be rogue console.log left somewhere in the mocha-typescript that logs during test execution, it seems the 'line' reporter prefixes console output from tests by appending the name of the test.

**Comment by henioStraszny** [comment]
I have some more findings:

I cannot reproduce it on my Windows 10, VS Code environment, but I can do this on my work Windows 7, VS Code environment and I can see the same behavior on Visual Studio Team Service **Hosted Agent**.

> I think the line reader I am using to read and write output from the mocha can not handle the output of the list reporter. I suspect the line reporter writes the name of the test and later when the test passes or fails it erases the line and rewrites it with the status and duration added. The mocha-typescript line reader however somehow strips any carriage return characters from the read line and the result is writing a second line. For now you can change the "list" reporter to the default one. I will keep the issue open, I may find a proper solution later.

I've modified **gulpfile.ts** so instead of list reporter it is using default reporter and now it works correctly on all environments.

> Another source for the problem may be rogue console.log left somewhere in the mocha-typescript that logs during test execution, it seems the 'line' reporter prefixes console output from tests by appending the name of the test.

Since it is reproducible on Visual Studio Team Service **Hosted Agent**, which is a build server worker, it always download new source codes and performs git install, so I doubt that there might be any rogue console.log.

Thank you @pana-cc for your fast response and support.

**Comment by pana-cc** [comment]
About the console.log I meant it may be something that I've missed in the mocha-typescript source code and got it incorrectly published, like this:
https://github.com/pana-cc/mocha-typescript/blob/master/index.ts#L217
But un-commented.

**Comment by henioStraszny** [comment]
Could be, perhaps it might be related to this:

[https://github.com/pana-cc/mocha-typescript/blob/master/bin/watch.ts#L116](https://github.com/pana-cc/mocha-typescript/blob/master/bin/watch.ts#L116)

**Comment by pana-cc** [comment]
I don't think so. This inspects the output from the 'tsc' proccess but during test run it should be silent. Tests run after successful typescript compilation. If tsc detects filechanges and start incremental compilation, the 'mocha' proccess is killed, so the two outputs are unlikely to interfere.

**Comment by pana-cc** [comment]
It turned out the "line" reporter is really rewriting lines, the watcher doesn't need line reader on the mocha output so I just piped the output. The multiple lines should appear well now. The fix is released in **mocha-typescript@1.0.22**.

**Comment by henioStraszny** [comment]
I've updated mocha-typescript but unfortunately problem with list reporter persists:

**Comment by pana-cc** [comment]
I have verified this and it seems to work properly.
This is the mocha.opts I am using:
```
--reporter list
--recursive
test/
```
And it is working well.
The ts-node and compiler registration is redundant with the mocha-typescript-watch, the mocha-typescript-watch will runt it typescript compiler and feed the produced .js files to mocha using type checking and incremental compilation, rather than the mocha's just-transpile.

You should pick one of the two, either use mocha-typescript-watch without the extension and compiler registration in the .opts or use the mocha watcher.

I can no longer reproduce the problem.
