### ISSUE TITLE
Skip testsuite if test fails

### ISSUE THREAD

**Issue by niklasdoerfler** [pana-cc/mocha-typescript#24]
Hi,

I'm trying to achive a unit test suite which first test tries to connect to a server. If this test fails I want to abort all following tests, because they rely on the server connection.

I need something like a skipOnError function. 
Does anybody know a solution for this problem?
Thanks!

**Comment by PanayotCankov** [comment]
I couldn't find skipOnError in mocha, perhaps I am not looking properly. Do you have example with this in some of the built in mocha UIs? On the other hand this looks promising: https://github.com/rprieto/mocha-steps so mocha-typescript can borrow something like @skipOnError suite decorator that would skip all tests in a suite after the first test failure.

**Comment by pana-cc** [comment]
This seems to work:
``` TypeScript
import { suite, test, context } from "mocha-typescript";

@suite class Suite {
    static skipRest: boolean = false;
    @context ctx: Mocha.IBeforeAndAfterContext;
    before() {
        if (Suite.skipRest) {
            this.ctx.skip();
        }
    }
    after() {
        if (this.ctx.currentTest.state === "failed") {
            Suite.skipRest = true;
        }
    }
    @test "one"() {
    }
    @test "two"() {
        throw "fail";
    }
    @test "three"() {
    }
}
```
I will try to provide a decorator for it later.

**Comment by pana-cc** [comment]
Supported since v1.1.0:
``` TypeScript
@suite(skipOnError)
class StockSequence {
    @test step1() {}
    @test step2() { throw new Error("Failed"); }
    @test step3() { /* will be skipped */ }
    @test step4() { /* will be skipped */ }
}
```
