### ISSUE TITLE
Sourcemap support for test files

### ISSUE THREAD

**Issue by tugayac** [pana-cc/mocha-typescript#25]
I was wondering if this was on the roadmap, as it doesn't seem like there's an option to tell `mocha-typescript` to use sourcemaps when printing stacktraces on test failures.

I workaround this right now by using [node-source-map-support](https://github.com/evanw/node-source-map-support) on top of my test files, but it would be great if it could be integrated into this project. Perhaps a flag like `--sourcemap` to enable sourcemaps?

**Comment by PanayotCankov** [comment]
I've been using node-source-map-support too. I think this is more of a node issue and is not closely interdependent, but at the same time it is important feature when you develop TypeScript. I do not think I will add this as dependency in mocha-typescript directly but probably it should be added to the scaffolding section and eventually to future project generator templates.

**Comment by pana-cc** [comment]
Added to REDAME.md
