### ISSUE TITLE
 Error in test difinition

### ISSUE THREAD

**Issue by derth** [pana-cc/mocha-typescript#29]
When i use this code:
@test("can have tests") {}

i get the error:
TS1240:Unable to resolve signature of property decorator when called as an expression.
  Cannot invoke an expression whose type lacks a call signature. Type 'ITest' has no compatible call signatures.

this code works ok:
@test "typescript also supports this syntax for method naming"() {}

**Comment by pana-cc** [comment]
Please use v1.0.23, i ll be on a vac. this week and wont be able to resolve the issue for a while.

**Comment by pana-cc** [comment]
Managed to reproduce it quite easily, installing @types/mocha with mocha-typescript does brake the `@test(name)` usage.

**Comment by pana-cc** [comment]
This should be fixed in 1.1.3 I've just published.
