### ISSUE TITLE
@class decorator is not available

### ISSUE THREAD

**Issue by gallayl** [pana-cc/mocha-typescript#30]
I've tried to use generated test classes with @class decorator (as it is described in the [readme](https://www.npmjs.com/package/mocha-typescript#generated-suites-and-tests)
I've tested with v __1.0.23__ and v __1.1.2__

Error msg.:
```
[ts] Module '"mocha-typescript"' has no exported member 'class'.
```

**Comment by pana-cc** [comment]
Use @suite. I've rewritten the doc and the @class is a mistake. It shouuld work in both 1.0.* and 1.1.* versions.
