### ISSUE TITLE
best practice for coverage?

### ISSUE THREAD

**Issue by shaunc** [pana-cc/mocha-typescript#36]
Can the documentation suggest/link to a best practice for code coverage? I'm using your package (thanks!), but it seems suggested tooling for istanbul with typescript uses mocha differently. It looks like ts-node is recommended. Can this package be made to work directly with typescript source code (using mocha `--compilers ts-node/register`)?

**Comment by pana-cc** [comment]
It should work with any typescript transpiler and source maps. Ideally when decorators become mainstream ES feature it won't be a TypeScript plugin anymore and will be usable in plain JS. I've already spent some time to make the plugin work with the mocha built in watcher, but this have nasty side effects (the way TS is transpilation does not behave properly when the transpilation depend on type information from other sources, e.g const enums). I think it worked with the awesome typescript loader. When I have a little bit free time I will try to add code coverage to the scafolding section.

**Comment by pana-cc** [comment]
The following works like a charm.
Instal `npm i nyc -D` as dev dependency.
Set the following npm scripts:
```
  "scripts": {
    "pretest": "tsc",
    "test": "nyc mocha --opts tests/mocha.opts",
    "watch": "mocha-typescript-watch"
  },
```
This will use `tsc` before running the tests to produce .js files out of the .ts files, using properly the tsconfig.json. Then when actually running the tests, it will use `nyc` command line tool to launch `mocha` and collect test coverage out of it.

To have source maps you need tsconfig.json like:
```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "experimentalDecorators": true,
        "sourceMap": true,
        "lib": [ "es6" ]
    }
}
```

To set mocha test files and options you need something like `tests/mocha.opts`:
```
--ui mocha-typescript
--require source-map-support/register
tests/test.js
```
And the actual tests at `tests/test.ts` that the `tsc` will use to generate the `tests/test.js` entry point for mocha:
```
import * as i from "../index";

@suite class Big {
    @test small() {
        i.big(0);
    }
    @test big() {
        i.big(200);
    }
}
```
At the root of your repo something like `reference.d.ts` to provide definitions for the test and suite globals:
```
/// <reference path="./node_modules/mocha-typescript/globals.d.ts" />
```
And the `index.ts` that is actually being tested:
```
export function big(n: number): boolean {
    if (n > 100) {
        return true;
    } else {
        return false;
    }
}
```

There are some points in the documentations that needs updates, I think mocha was picking tests/mocha.opts by default but it now must be provided through the command line. tests/test.ts is mixed with test/tests.ts etc. I think it is time to actually make a seed repo with that setup.

**Comment by pana-cc** [comment]
Hi,
The README.md has been updated. There is a seed repo now at:
```
https://github.com/pana-cc/mocha-typescript-seed
```
You can check how it uses the tsc, nyc and the mocha tools to generate test coverage.
Source maps work perfectly well with nyc, and the used reporter generates HTML with the TS version of the source and highlights non-covered statements.
The v1.1.7 has been published to update the npm readme.

**Comment by shaunc** [comment]
Thanks! :) +1
