### ISSUE TITLE
[QUESTION] - How I can change the test title from a decorator?

### ISSUE THREAD

**Issue by Amitesh** [pana-cc/mocha-typescript#383]
## Question

How I can change the test title from a decorator?

In Mocha execution, we have `grep` feature which helps to execute the matched test cases. [https://mochajs.org/api/mocha#grep]
I am looking for a similar solution that helps me to exclude the test on compile time using a decorator.

Example: Let say, I have a set of tests, and all tests may not be applicable to all different types of users. I want to exclude a few tests based on the type of users. I like to build a decorator which help me to achieve this. 

It will help to apply the same logic for a setting-driven application where we have tons of customization and settings.

```js
import { suite, test } from "@testdeck/mocha";
import { expect } from 'chai';

const UserType = {
  'customer': 1,
  'admin': 2
}
@suite
class UserTests {

  // Execute the test by mocha using grep if user type is 'admin'
  // or exclude this test for user type 'customer'
  @runForUserType('admin') // custom decorator
  @test "should able to view reports" (){
    // some assertions....
    expect(true).to.equal(true);
  } 
}

/* 
Set mocha grep as
1. grep: /admin/i
2. grep: /admin|supervisor/i
*/
```
or Is there a way to skip the current test from my custom decorator? if yes then a sample will be helpful. Thanks.

**Comment by silkentrance** [comment]
@Amitesh thanks for your question.

I fear that it is not possible to change the test name (aka title) based on some condition.

Perhaps you should rethink your testing strategy, e.g. add a test for an admin user and one for a customer user.
The latter (customer) should be expected to fail as the user does not have the permission to view the reports.

**Comment by silkentrance** [comment]
@Amitesh There is a skip by condition option, see https://testdeck.org/pages/guide/advanced_tests#skipping-tests---

**Comment by Amitesh** [comment]
Thank you @silkentrance for answering it.

Here is what I have tried which is able to mark the test as skipped in allure report but it also executes the test body.

```javascript
// spec file
import { default as AllureReporter } from '@wdio/allure-reporter';
store.set('skipSettingKey', 'admin-user');

@mySkip('admin-user')
  @test
  public MyTest1() {
    AllureReporter.addStep('Step: running test- MyTest1');
    AllureReporter.startStep('start of step');
    AllureReporter.addStep('step body');
    AllureReporter.endStep('passed');
    expect(5).toBeGreaterThan(4);
  }

// file decorator.ts
export function mySkip(value: string) {
  return (target: any, propertyKey: string, descriptor: PropertyDescriptor) => {
      const original = descriptor.value;

      if (typeof original === 'function') {
          descriptor.value = function(...args) {
              try {
                AllureReporter.addStep(value);
              } catch (e) {
                  console.error(`[ERROR] Failed to decorate ${target.constructor.name}.${propertyKey}: ${e}`);
              }
              const tagToSkip = store.get('skipSettingKey'); // here store is a service which give the key at runtime
              
              if(tagToSkip === value){
                this[context].skip();
              }
              return original.apply(this, args);
          };

          for (let prop of Object.keys(original)) {
              if(original.hasOwnProperty(prop) && prop.startsWith('__testdeck_')) {
                  descriptor.value[prop] = original[prop]
              }
          }
      }
      return descriptor;
  };
}
```

**Comment by silkentrance** [comment]
@Amitesh  you are always calling the original function.

**Comment by Amitesh** [comment]
Thanks @silkentrance
