### ISSUE TITLE
[BUG] Showing test retries (4 times ) for a test in report but retries not set

### ISSUE THREAD

**Issue by Amitesh** [pana-cc/mocha-typescript#384]
## Testdeck Version

e.g. v0.0.5

## Testdeck Package

 - [ true] `@testdeck/core`
 - [ true] `@testdeck/mocha`
 - [ ] `@testdeck/jasmine`
 - [ ] `@testdeck/jest`
 - [ ] `@testdeck/vitest`
 - [ ] `@testdeck/di-typedi`
 - [ ] unsure

## NodeJS Version

 - [true ] 18
 - [ ] 16
 - [ ] 14
 - [ ] all
 - [ ] other:

## Mocha / Jasmine / Jest / Vitest / Typedi Version

 - Mocha: true
 - Jasmine:
 - Jest:
 - Vitest:
 - Typedi:

### Operating System

 - [ ] Linux
 - [true ] Mac OS X
 - [ ] Windows 10
 - [ ] Windows 11
 - [ ] Other:

### Actual Behaviour

The test has been retried 3 times. it should be executed once only.

### Expected Behaviour

Test should run once only.

### Additional Information
I have created a sample project for testing. it has screenshots as well for reference.
https://github.com/Amitesh/test-decorator/tree/bug/retries-3-times/e2e

<img width="876" alt="Screenshot 2023-05-18 at 12 23 42 AM"
 src="https://github.com/testdeck/testdeck/assets/42645/582a735d-6e54-4018-9aea-6a1ef4e7bb98">
<img width="1444" alt="Screenshot 2023-05-18 at 12 24 21 AM" src="https://github.com/testdeck/testdeck/assets/42645/d8eb4cf3-b5ea-4df9-a89a-12aa14c8133b">

<img width="1444" alt="Screenshot 2023-05-18 at 12 25 45 AM" src="https://github.com/testdeck/testdeck/assets/42645/f19c5506-7236-457f-a922-c02e4fc5412c">

**Comment by Amitesh** [comment]
I have further tested it with nodejs 14.21.3 it is working fine and there are no any retries log in the Allure report.

When I ran it in nodejs v18.12.1 then only I am getting the retires logs issue in Allure. I observed that for each hook like @test, before, after, etc adding one entry in the Allure report. 
I am further investigating but if you have any pointer regarding this then it will be helpful. Also if you have any architecture diagrams or docs related to the implementation share those here so that I can predict to start from there. thanks.

**Comment by Amitesh** [comment]
Hi,

After investifating it more I found it is issue with @wdio/allure-reporter ^8.10.2 but it works fine with @wdio/allure-reporter@^7.14.1.

Here is a issue reported on wdio github- https://github.com/webdriverio/webdriverio/issues/10393.

**Comment by Amitesh** [comment]
Closing this issue here. Thank you.

**Comment by HimanshuD-Groove** [comment]
@Amitesh any reason for closing this bug? I also see a similar issue? The bug you cited in your previous comment is a different issue.

**Comment by HimanshuD-Groove** [comment]
@Amitesh I think this bug is related to https://github.com/webdriverio/webdriverio/pull/10176
