### ISSUE TITLE
[FEATURE] Skip the test from Mocha execution using grep option

### ISSUE THREAD

**Issue by Amitesh** [pana-cc/mocha-typescript#385]
## Testdeck Version
latest

## Description

Use annotation to skip the test at the time of compilation from the Mocha. 

Defining situation:
I am working on an application that is built for a SaaS product that has 60+ features/modules and 3000+ test cases. It requires verifying the feature or sub-feature we run the test to target very specific test cases. We use the Mocha `grep` option which helps to choose only run those tests only. We have added tags, some settings value dynamically in the title which evaluates dynamically before Mocha compilation. for example:

```javascript
// file - helper.ts
export default getUserPoint(){
  // Get the customer user points from backend dynamically
  const points = 100; // assume it is 100
  return points;
}

export default isApplicableForCurrentClient(settings){
  // fetch the current client (for which saas product is running) settings from backend dynamically if the current feature is enabled or not for given settings
  const enabled = false; // assuming it is false for now
  return enabled;
}

// file - test.spec.ts
describe('feature-name: about sub-feature', function () {
    it(`should show the offer if the user coin points greater than ${getUserPoint()} #coins #points isSettingEnabled=${isApplicableForCurrentClient('point-settings')}`, function () {
      // ...
    });
});
```

Once the above code compiles then it will look like below:

```javascript
// file - test.spec.ts
describe('feature-name: about sub-feature', function () {
    it(`should show the offer if the user coin points greater than 100 #coins #points isSettingEnabled=false`, function () {
      // ...
    });
});
```

```javascript
// configure wdio.config.ts for mocha ops with grep
...
mochaOpts: {
  ui: 'bdd',
  timeout: 60000,
  grep: 'isSettingEnabled=true'
},
...
```

As per the above `grep` settings, it will only run those tests which are applicable to the current client and customer. It enables running the test for many different types of clients and its customer without setting up the test data every time in e2e test. it will pull the real settings and run the test accordingly.

The best approach of **Mocha** is, these tests which don't match the grep will be excluded at the mocha compilation itself. it will not be skipped at execution time hence it saves lots of test run execution time. It helps get the verification report quickly.

I know, if we add all these in the test title still in TestDeck then it can be achieved but sometimes it makes my test case title ugly and loses the readability. I want the same efficiency with the help of the TestDeck annotation feature without losing the test title readability.
Like below:

```javascript
// file - test.spec.ts
@suite('feature-name: about sub-feature')
class MySuite{

@addUserPoints() // fetch the points and replace the pattern in the title `<replace-with-point>`
@tags(['#coins', '#points'])
@isSettingEnabled('point-settings') // 'setting-key-name', add title like `isSettingEnabled=true | false`
@test 'should show the offer if the user coin points greater than <replace-with-point> '() {
  // ...
  }
}
```

```log
npm test

  feature-name: about sub-feature
    ✓ should show the offer if the user coin points greater than 100

  1 passing (1s)
  0 failing

```

I appreciate it if you guide how to achieve it using or enhancing TestDeck.

Techstack
- [webdriver.io](https://webdriver.io/) - latest
- [Mocha](https://mochajs.org/) - latest
- [Allure Reporter](https://webdriver.io/docs/allure-reporter/) - 7.x.x
- [TestDeck](https://testdeck.org/) - latest
- [Nodejs](https://nodejs.org/en/about) - 18.x.x

Reference links:
- [https://mochajs.org/#-grep-regexp-g-regexp](https://mochajs.org/#-grep-regexp-g-regexp)
- [http://www.petecorey.com/blog/2016/07/25/mochas-grep-flag/](http://www.petecorey.com/blog/2016/07/25/mochas-grep-flag/)

**Comment by silkentrance** [comment]
For parametrising the test name, see https://testdeck.org/pages/guide/parametrised_tests.
As for conditionally running individual tests or suites, see 

- https://testdeck.org/pages/guide/advanced_suite#skipping-suites---
- https://testdeck.org/pages/guide/advanced_tests#skipping-tests---

**Comment by silkentrance** [comment]
@Amitesh I know it has been a long time, but have you succeeded with the above provided information? May we close the issue?

**Comment by silkentrance** [comment]
For what it is worth, it is already provided and the responsibility lies in the ability of the test engineer to apply proper means to its test suites and test cases.
