### ISSUE TITLE
[FEATURE] Add `beforeAll`, `afterAll`, `beforeEach`, `afterEach` decorators for `jest`

### ISSUE THREAD

**Issue by ivankrtv** [pana-cc/mocha-typescript#387]
## Testdeck Version

Version: 0.3.3

## Description

It would be nice have a `beforeAll`, `afterAll`, `beforeEach`, `afterEach` decorators for use this functions in test suites

**Comment by silkentrance** [comment]
We have something similar, see

- beforeEach/afterEach: https://testdeck.org/pages/guide/advanced_suite#instance-lifecycle-hooks---
- beforeAll/afterAll: https://testdeck.org/pages/guide/advanced_suite#static-lifecycle-hooks---

see also the notes on inheritance and lifecycle hook chaining:
- https://testdeck.org/pages/guide/inheritance#static-lifecycle-hook-chaining
- https://testdeck.org/pages/guide/inheritance#instance-lifecycle-hook-chaining
