### ISSUE TITLE
Obscure error message "Run mocha. Exited with 1".

### ISSUE THREAD

**Issue by bijoutrouvaille** [pana-cc/mocha-typescript#42]
Hello and thanks for a cool plugin. 

`mocha-typescript-watch` does not forward mocha's error messages for some reason. Every so often, I run into an inconvenience when I accidentally import modules that don't resolve to a file, e.g. `import {x} from './some-file-that-does-not-exist'`, which causes mocha to fail with `Error: Cannot find module './some-file-that-does-not-exist'`. To actually see that message, currently, I have to stop `mocha-typescript-watch`, find the mocha executable in `node_modules` and run it manually in the transpiled directory, after I remember how to do it. It would be really nice to see a smoother experience there.

Thanks again.

**Comment by PanayotCankov** [comment]
Hi @bijoutrouvaille,

The stderr hadn't been piped.
It is now in mocha-typescript@1.1.8.

Regards,
