### ISSUE TITLE
Async/Await Resolution Method Not Specified

### ISSUE THREAD

**Issue by raceloop** [pana-cc/mocha-typescript#43]
Hi, 

I have two pieces of code which do the same thing. 

Method 1 without `Await/Async` (this works):
```
@test()
    @timeout(20000)
    'should make one charge'(done) {
        const cards = this.stripeConnect.loadCards("cus_B8Fbacc6tlHrhV").then(cards => {
            let card = cards[0];
            let metadata = {chargeFor: "test charge"};
            this.stripeConnect.createChargeByCard("acct_xxxxxxxxxxxxx", card.id, "cus_xxxxxxxxxxxx", 10000, 50, "EUR", "a unit test generate charge", this.idempotencyKey, metadata).then(charge => {
                console.log("charge", charge);
                console.log("charge.outcome.network_status", charge.outcome.network_status);
                expect(charge.outcome.network_status).to.equal('approved_by_network');
            }).then( () => {
                done();
            }).catch((error) => {
                done(error);
            });
        });
    };
```
Method 2 is the same function with `Await/Async` (this doesn't work):
```
    @test()
    @timeout(20000)
    async 'should make a second charge'(done): Promise<void> {
        const cards = await this.stripeConnect.loadCards("cus_B8Fbacc6tlHrhV");
        let card = cards[0];
        let metadata = {chargeFor: "test charge"};
        let charge = await this.stripeConnect.createChargeByCard("acct_xxxxxxxxxxxxx", card.id, "cus_xxxxxxxxxxxx", 10000, 50, "EUR", "a unit test generate charge", this.idempotencyKey, metadata);
        expect(charge.outcome.network_status).to.equal('approved_by_network');
        done();
    };
```

Method 2 returns the following error:

`Resolution method is overspecifed. Specify a callback *or* return a promise; not both. `

To me this all looks ok.. I have looked through the forums and someone else has suggested that both methods are valid (which they should be). 

Is this a known issue or am I doing something wrong? What is the correct way to use `async/await` with this framework?

Many thanks

JT

**Comment by pana-cc** [comment]
Mocha in general doesn't work like that.
You have two types of async-ness.

One would be callback based, this gets "done" as argument in the function provided to the test `it("asd", function(done) {});`, the `done` has to be called once.

The second is Promise based, if a function returns a promise, it is awaited and catched, when fulfiled the test passes, when it throws the test fails.

Now on the other hand having "async" methods explicitly makes a function return a promise. Like in the second example. But in it you also obtain a "done" function. So mocha can't decide whether it should wait for the done to be called or to wait for the promise to be resolved... In the second case I think you can delete the `done` argument and don't call done() at the end.
