### ISSUE TITLE
Retry tests

### ISSUE THREAD

**Issue by mad-gooze** [pana-cc/mocha-typescript#46]
Hello!

Is it possilbe to use [mocha's retry tests feature](http://mochajs.org/#retry-tests) from mocha-typescript?

**Comment by mad-gooze** [comment]
I have managed to call retries() from mocha context, but it seems that it is not working properly.
Please see this examples:
https://github.com/mad-gooze/mocha-typescript/blob/retries/retries-in-test.ts
https://github.com/mad-gooze/mocha-typescript/blob/retries/retries.ts

If I call `this.mocha.retries` in `@test` (1st example), everything is ok
```
Hello world: calls 0
Hello world: calls 1
Hello world: calls 2
Hello world: calls 3
```

But if I do it in `before()` function (2nd example), it is ignored.
```
Hello world: calls 0
```
The same happens if I do it in `static before()`. 

While first variant is working, I would like to use the second one to enable retries in all of my test suites derived from a single BaseTest.

Is that a bug in mocha-typescript or am I doing something wrong?

Thnx

**Comment by PanayotCankov** [comment]
I have no idea why it is not working, I will have to debug it.

On the other hand this is suitable for a "retries" function in mocha-typescript so it can be used as:
``` TypeScript
@suite(retries(5), timeout(10)) class Suite { ... }
// or 
@suite @retries(5) @timeout(10) class Suite { ... }
// as well as on the instance methods
@suite class Suite {
  @test(retries(5)) method1() {}
  // or
  @test @retries(5) method2() {}
}
```

**Comment by mad-gooze** [comment]
`@retries` looks cool (if it will also affect derived classes).

**Comment by pana-cc** [comment]
V 1.1.10 is live now. It should support @retries.
I am not sure this will be polymorphic (inherited from a base class):
```
@suite(@retries(2)) class Suite {}
```
But I think using @slow @timeout and @retries as decorators should be:
```
@suite @retries(2) class Suite {}
```
Polymorphism is not well handled (as in its the way it is, I didn't put any special thought onto it) So I will open this issue open for now as reminder. At some point I will have to handle the first case and figure out how these settings are inherited, also whether tests in base classes will be executed when the base class is derived etc.

**Comment by pana-cc** [comment]
@mad-gooze would you give it a try?
