### ISSUE TITLE
Handle Inheritance

### ISSUE THREAD

**Issue by PanayotCankov** [pana-cc/mocha-typescript#47]
Make sure that:
 - [ ] decorators from base classes are inherited into derived classes
 - [ ] decorators from base classes can be overridden by derived classes
 - [ ] "traits" from base classes are inherited into derived classes
 - [ ] "traits" from base classes can be overridden by derived classes
 - [x] tests from base classes are or are not executed by derived classes. 
    I am not sure about the proper behaviour, but whatever it is it should be stable reliable tested and documented.

**Comment by silkentrance** [comment]
@PanayotCankov with #72 in place we can now override tests from super classes.

**Comment by silkentrance** [comment]
@PanayotCankov I do not understand what you mean by

- decorators from base classes are inherited into derived classes
- decorators from base classes can be overridden by derived classes
- "traits" from base classes are inherited into derived classes
- "traits" from base classes can be overridden by derived classes

**Comment by silkentrance** [comment]
I think that we can call this to be solved. Inheriting from abstract base classes that are not `@suites` themselves works just fine for me, as of #71 and #72. If you have any other requirements than #84, please reopen a new issue.
