### ISSUE TITLE
Is it possible to debug code when tests are running?

### ISSUE THREAD

**Issue by Naktibalda** [pana-cc/mocha-typescript#56]
I've tried to debug using PhpStorm and node-inspector, but nothing stops test execution.
This is specific to mocha-typescript, because PhpStorm can debug code when it executes generated javascript code.

Would upgrading to 2017.3 EAP help in this aspect?

**Comment by PanayotCankov** [comment]
I am debugging with VSCode and it works like a charm. From what I know is setting up your tsconfig.json to generate source maps should be pretty much enough. I will give it a try when I have some free time.

**Comment by Naktibalda** [comment]
Sorry, probably it was my fault.

Today I tried debugging again and it works perfectly after I fixed an error which looked like a failed expectation, but it was actually happening at the place where I was setting that expectation (callArg instead of callsArg in sinon mock).
