### ISSUE TITLE
Root level hooks?

### ISSUE THREAD

**Issue by chadbr** [pana-cc/mocha-typescript#57]
I need to do some 'root hooks'

https://mochajs.org/#root-level-hooks

specifically and "after" hook to cleanup an external process I'm running...

is this possible with mocha-typescript? I'm struggling to get the function "picked up" by mocha.

thanks much -- Chad

**Comment by pana-cc** [comment]
before, beforeEach, after, afterEach all behave as in "regular mocha" and the @suite @test act as describe and it. Just throw the after in a test module somewhere on a root level. I planed mocha-typescript to help in appium and design page objects and have root hooks to start stop decices. It should just work. I am not on a computer right now but if you can't make it work I will check it later.

**Comment by chadbr** [comment]
thanks @pana-cc -- unfortunately I'm not having any luck.

I've added this code as `before-and-after.spec.ts`

```
async function before(): Promise<void> {
  console.log('gg before');
}

async function after(): Promise<void> {
  console.log('gg after');
}

```

If I add it to my `src` directory, none of my tests run -- odd behavior:

```
Chads-MBP:myapp-backend chadbr$ yarn test
yarn run v1.2.1
warning package.json: License should be a valid SPDX license expression
$ mocha --recursive --require ts-node/register -R spec ./**/*.spec.ts --no-timeouts --exit --environment local


  0 passing (1ms)

✨  Done in 1.26s.
Chads-MBP:myapp-backend chadbr$
```

If I add it in a sub dir to `src` -- for example 'src/utilities' - the mocha run just hangs:

```
Chads-MBP:myapp-backend chadbr$ yarn test
yarn run v1.2.1
warning package.json: License should be a valid SPDX license expression
$ mocha --recursive --require ts-node/register -R spec ./**/*.spec.ts --no-timeouts --exit --environment local
^C

```

any ideas welcomed.

Thanks - Chad

**Comment by chadbr** [comment]
adding export to the functions keeps the tests from hanging -- but they're still not 'hooked'

changing them to be non-async had no effect either...

```
export async function before(): Promise<void> {
  console.log('gg before');
}

export async function after(): Promise<void> {
  console.log('gg after');
}

```

```
export function before() {
  console.log('gg before');
}

export function after() {
  console.log('gg after');
}

```

**Comment by chadbr** [comment]
Happy New Year!

Just trying to give this a little bump -- if you get a few minutes.

thanks - Chad

**Comment by pana-cc** [comment]
I am sorry for the extremely huge delay in response but it's been a though year. Now the seed has the async before and after hooks: https://github.com/pana-cc/mocha-typescript-seed/blob/057e1cfa9d184548d660437b457ff32cc511460f/test/test.ts#L12
I am closing this issue.

**Comment by chadbr** [comment]
No worries! Thanks for your time.

I hope your year improves - it's only January!
