### ISSUE TITLE
Integration with mocha-testdata

### ISSUE THREAD

**Issue by arieldf** [pana-cc/mocha-typescript#60]
Hi!

Thanks for this wonderful library.

I would like to integrate mocha-testdata (https://github.com/pandell/mocha-testdata/) when using mocha-typescript. I would basically want something like this:

	@testData([1, 2, 3])
	@test
	public UnitOfWork_ScenarioUnderTest_ExpectedResult(arg1, arg2, arg3): void {
		// Arrange
		const sut = new Calculator()

		// Act
		const sum = sut.add(arg1, arg2, arg3);

		// Assert
		Assert.equal(sum, 6);
	}

Does anyone know how to proceed? I think this would be a great feature to have.

Best regards,
Ariel

**Comment by arieldf** [comment]
Here is an example of use with xUnit that I use when writing C#: http://hamidmosalla.com/2017/02/25/xunit-theory-working-with-inlinedata-memberdata-classdata/

and further more advance stuff using AutoFixture/AutoMoq:

https://engineering.thetrainline.com/an-introduction-to-xunit-moq-and-autofixture-995315f656f

By clever use of typemoq (https://github.com/florinn/typemoq), InversifyJS and possibly FakerJS, maybe it is possible to make something similar?

**Comment by arieldf** [comment]
I have been experimenting with this for some time today.  I have made an annotation that works in isolation (calling a method with just my annotation inside the test function body works, but not really what I want). I assume it clashes with the @test annotation due to the **done** argument that will be the first arg to the test function. I am not able to append new arguments after **done**.

Do you have any advice @pana-cc ?

**Comment by pana-cc** [comment]
Hi,

I think you could use the “Generated Suites and Tests” section of the readme. It is something similar. This feature request came up some time ago so it may be worth to put some effort into generating dynamic test cases with mocha-typescript.

**Comment by arieldf** [comment]
Thanks for the answer!

I think this would be a fantastic feature. I would like a lot to contribute here, but I am not getting the stuff I try to build to work.

Thanks again.

**Comment by arieldf** [comment]
@pana-cc Do you have some resources or other lib I can look at for inspiration? I would be very happy contributing here.

**Comment by silkentrance** [comment]
@pana-cc in junit5 there are so called ParameterProviders that you can use for generation of the parameters for a given parameterised test. in addition there is an annotation for use at the test method level that references the parameter provider impl and will run the same test multiple times. Perhaps we could implement this as a trait, e.g.

```
@test(parameters(...)) "test method with parameters"(done, param1, param2, ...) {
}
```

of course this will pose some problems with async test functions, but we could always wrap and pass in additional arguments to the underlying test impl.

**Comment by pana-cc** [comment]
I am not worried about the args, with decomposition we can also have the "parameters" attribute to expect an array, and then treat test methods with one param as sync, and two params as async. And multiple params can just be split using decomposition like:
```
@test(parameters({ a: 1, b: 2 }, { a: 2, b: 3}) "my test"({a, b}, done) {
  // do async stuff with a and b
}
@test(parameters({ a: 1, b: 2 }, { a: 2, b: 3}) "my test"({a, b}) {
  // do sync stuff with a and b
}
```
The `length` of the above functions will be 2 and 1 respectively.
And you can easily work with `a` and `b` in the method body.

I just couldn't figure out decent type inference for these parameters.

Then the implementation in mocha-typescript that calls the underlying "it" should just check if there is a "parameters" array, and if there is one, it should register multiple tests instead of just one.

**Comment by silkentrance** [comment]
@pana-cc i was about to implement something along the way of synthesizing additional `it`s by injecting new test methods to the test class during application of the decorator, which then could be picked up during execution of the tests.

similarly to junit5 i would allow the user to define a custom template or use a default template for defining the test method's name, e.g. `template $${parameters}...`.

**Comment by pana-cc** [comment]
The code is here:
https://github.com/pana-cc/mocha-typescript/blob/a092bc0eb58c10a2df433408a8dff33a8cc82794/index.ts#L209
It should be something like:
```
if (params) {
    params.foreach(parameter => {
        testFunc(nameForParameters(parameter), noname(function (this: Mocha.ITestCallbackContext, done) {
            applyDecorators(this, prototype, method, instance);
            applyTestTraits(this, instance, method);
            return method.call(instance, parameter, done);
        }));
    });
} else {
    testFunc(testName, noname(function (this: Mocha.ITestCallbackContext, done) {
        applyDecorators(this, prototype, method, instance);
        applyTestTraits(this, instance, method);
        return method.call(instance, done);
    }));
}
```
And the sync version is several lines below this.
the `method.call(instance, parameter, done)` will provide the proper param to the class method, while the testFunc will generate a callback with proper signature to be passed to mocha. I can't think of a good naming mechanism. You can treat the method name itself a template string, or use the `@name` with lambda like:
```
@test
@parameters({ a: 1, b: 2 }, { a: 2, b: 3 })
@name({ a, b } => `test ${a} plus ${b}`)
testingAplusB({a, b}) {
  // assert a + b
}
```
And use the function provided with `@name` as the `nameForParameters` in the above snippet.

**Comment by silkentrance** [comment]
@pana-cc great stuff. very helpful. i will look into this when I find the time. atm i have only implemented the @parameters trait/decorator.

**Comment by silkentrance** [comment]
@pana-cc the naming solution based on the parameters is actually very good. there exists something similar in junit5.

**Comment by silkentrance** [comment]
With #82 in place I think that we can consider this to be resolved.
