### ISSUE TITLE
The seed repository throws an error upon npm install

### ISSUE THREAD

**Issue by binki** [pana-cc/mocha-typescript#66]
```
ohnobinki@gibby ~ $ git clone git@github.com:pana-cc/mocha-typescript-seed
Cloning into 'mocha-typescript-seed'...
cd remote: Counting objects: 39, done.
Receiving objects: 100% (39/39), 5.75 KiB | 0 bytes/s, done.
Resolving deltas: 100% (9/9), done.
remote: Total 39 (delta 0), reused 0 (delta 0), pack-reused 39
ohnobinki@gibby ~ $ cd mocha-typescript-seed
ohnobinki@gibby ~/mocha-typescript-seed $ npm install

> mocha-typescript-seed@1.0.0 prepare /home/ohnobinki/mocha-typescript-seed
> tsc

node_modules/@types/mocha/index.d.ts(41,15): error TS2451: Cannot redeclare block-scoped variable 'describe'.
node_modules/@types/mocha/index.d.ts(46,15): error TS2451: Cannot redeclare block-scoped variable 'suite'.
node_modules/@types/mocha/index.d.ts(47,15): error TS2451: Cannot redeclare block-scoped variable 'it'.
node_modules/@types/mocha/index.d.ts(50,15): error TS2451: Cannot redeclare block-scoped variable 'test'.
node_modules/@types/mocha/index.d.ts(56,6): error TS2300: Duplicate identifier 'MochaDone'.
node_modules/mocha-typescript/globals.d.ts(51,13): error TS2451: Cannot redeclare block-scoped variable 'suite'.
node_modules/mocha-typescript/globals.d.ts(52,13): error TS2451: Cannot redeclare block-scoped variable 'test'.
node_modules/mocha-typescript/globals.d.ts(54,13): error TS2451: Cannot redeclare block-scoped variable 'describe'.
node_modules/mocha-typescript/globals.d.ts(55,13): error TS2451: Cannot redeclare block-scoped variable 'it'.
node_modules/mocha-typescript/index.d.ts(15,11): error TS2300: Duplicate identifier 'MochaDone'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mocha-typescript-seed@1.0.0 prepare: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mocha-typescript-seed@1.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ohnobinki/.npm/_logs/2018-04-22T20_30_05_244Z-debug.log
```

I’m trying to figure out how to get the project to work, but the instructions leave me confused. I was going to try to use the seed and figure out how it was working, but it had these errors. Could the seed repository be fixed back into an example of how to get mocha-typescript to work?

**Comment by pana-cc** [comment]
I will check this tonight.

Also it would be of great help for us to increase the adoption of this plugin if you could share what is confusing in the documentation. Could you share your experience, what parts your read what steps you took and what were the issues you've faced?

**Comment by dcharbonnier** [comment]
#26 is back

**Comment by pana-cc** [comment]
There are 5 broken types:
```
declare var suite: Mocha.IContextDefinition;
declare var test: Mocha.ITestDefinition;
declare var describe: Mocha.IContextDefinition;
declare var it: Mocha.ITestDefinition;
interface MochaDone {
    (error?: any): any;
}
```
Have became:
```
declare const suite: Mocha.IContextDefinition;
declare const test: Mocha.ITestDefinition;
declare const describe: Mocha.IContextDefinition;
declare const it: Mocha.ITestDefinition;
type MochaDone = (error?: any) => void;
```
And can no-longer be redeclared by the mocha-typescript, where `const` are `var`, and the `type MochaDone` is `interface MochaDone` probably similar to earlier versions of `@types/mocha`.

TBD: Whether we can roll back these changes in `@types/mocha` or we will have to figure out a solution in `mocha-typescript`.

**Comment by pana-cc** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/bbe066cb55940c6047d3b43e9e9a02e576afd957

**Comment by cspotcode** [comment]
@pana-cc 

Thanks for pinging me.

`@types/mocha` should be moved from `devDependencies` to `dependencies`, not `peerDependencies`.  Right?

Converting `interface MochaDone` to `type MochaDone` was only done to please the linter.  If it's causing problems, we should definitely revert it.  (Here's the commit: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/48004042ddf801b3e6c0ff22388af70bf6e6a352)

**Comment by pana-cc** [comment]
@binki this should be resolved now.
I've added `@types/mocha` as dependency.
