### ISSUE TITLE
Wrapping tostring for annotated tests

### ISSUE THREAD

**Issue by richardspence** [pana-cc/mocha-typescript#73]
When using Karma test runner, the test runner toStrings() method implementations for rendering the html output.

Currently using karma runner you would get this when inspecting the method:
![image](https://user-images.githubusercontent.com/9914123/40564186-9723610a-601c-11e8-99a4-0f88035ef736.png)

## The fix:
Wrap tostring() to the inner function.
This change corrects the karma html viewer to show the correct test method implementation:
![image](https://user-images.githubusercontent.com/9914123/40564111-4eaac08a-601c-11e8-9cab-6bc1bb2a4db7.png)

PR: #68

**Comment by silkentrance** [comment]
This was fixed with #95.
